Add init-sdmmc
Adlink-ROS/rootOnStorage pull request #1
Opened 2022-03-01 03:32 UTC by DanielHo-BS

2022-03-23 09:14 UTC, evshary requested changes

2022-03-23 09:14 UTC, evshary commented on sdmmc/copy-rootfs-sdmmc.sh
> +sudo mkdir /mnt
I think we don't need to recreate /mnt folder.

2022-03-23 09:14 UTC, evshary commented on sdmmc/init-sdmmc.sh
> +sudo umount /dev/mmcblk1p1
We don't need to split the script into two parts.

2022-03-24 00:39 UTC, DanielHo-BS commented on sdmmc/copy-rootfs-sdmmc.sh
> +sudo mkdir /mnt
OK.

2022-03-24 00:39 UTC, DanielHo-BS commented on sdmmc/init-sdmmc.sh
> +sudo umount /dev/mmcblk1p1
OK

2022-03-24 00:44 UTC, DanielHo-BS reviewed
Done the request changes

2022-03-24 02:06 UTC, evshary commented
LGTM

2022-03-24 02:06 UTC, merged